-- DataDock Tarification Dynamique
-- Bootstrap minimal autorise
-- Aucune table supplementaire de tarification n'est creee ici.

CREATE TABLE DP_PORT_CONFIG (
    PORT_ID NUMBER PRIMARY KEY,
    PORT_NAME VARCHAR2(120 CHAR) NOT NULL,
    LATITUDE NUMBER(10,6) NOT NULL,
    LONGITUDE NUMBER(10,6) NOT NULL,
    IS_ACTIVE VARCHAR2(5 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DP_PRICE_RECOMMENDATION_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    IDESPECE NUMBER,
    PORT_ID NUMBER,
    BASE_PRICE_TND NUMBER(10,3) NOT NULL,
    RECOMMENDED_PRICE_TND NUMBER(10,3) NOT NULL,
    WEATHER_SCORE NUMBER(5,2),
    RISK_SCORE NUMBER(5,2),
    FRESHNESS_SCORE NUMBER(5,2),
    EXPLANATION_TEXT VARCHAR2(500 CHAR),
    API_SOURCE VARCHAR2(120 CHAR),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DP_LOG_SPECIES FOREIGN KEY (IDESPECE) REFERENCES ESPECES (IDESPECE),
    CONSTRAINT FK_DP_LOG_PORT FOREIGN KEY (PORT_ID) REFERENCES DP_PORT_CONFIG (PORT_ID)
);

INSERT INTO DP_PORT_CONFIG (PORT_ID, PORT_NAME, LATITUDE, LONGITUDE, IS_ACTIVE)
VALUES (1, 'La Goulette', 36.818970, 10.305080, 'Y');

INSERT INTO DP_PORT_CONFIG (PORT_ID, PORT_NAME, LATITUDE, LONGITUDE, IS_ACTIVE)
VALUES (2, 'Bizerte', 37.274420, 9.873910, 'Y');

COMMIT;
