#include "navirespage.h"
#include "ui_navirespage.h"
#include "navire.h"
#include "navirecruddialog.h"

#include <QDebug>
#include <QGraphicsDropShadowEffect>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QMessageBox>
#include <QPushButton>
#include <QSqlRecord>
#include <QTableWidgetItem>
#include <QToolButton>
#include <QFileDialog>
#include <QPdfWriter>
#include <QPainter>
#include <QTextStream>
#include <QDate>
#include <QDateTime>
#include <QMenu>
#include <QAction>

NaviresPage::NaviresPage(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::NaviresPage)
{
    ui->setupUi(this);

    setObjectName("NaviresCrudPage");

    addButton = ui->btnAddNavire;
    refreshButton = ui->btnRefresh;
    exportButton = ui->btnExport;
    sortCombo = ui->comboSortField;
    sortOrderCombo = ui->comboSortOrder;
    searchCombo = ui->comboSearchField;
    searchEdit = ui->searchBar;
    tableCard = ui->tableCard;
    table = ui->tableNavires;

    // Set up export drop-down menu
    QMenu *exportMenu = new QMenu(this);
    QAction *actionPdf = exportMenu->addAction(tr("Exporter en PDF"));
    QAction *actionCsv = exportMenu->addAction(tr("Exporter en CSV"));

    exportMenu->setStyleSheet(
        "QMenu { background-color: white; border: 1px solid #e2e8f0; border-radius: 6px; padding: 4px; font-size: 13px; }"
        "QMenu::item { padding: 6px 24px 6px 12px; border-radius: 4px; color: #1e293b; }"
        "QMenu::item:selected { background-color: #f1f5f9; color: #5390D9; font-weight: bold; }"
    );

    exportButton->setMenu(exportMenu);

    connect(actionPdf, &QAction::triggered, this, [this]() {
        QString fileName = QFileDialog::getSaveFileName(this, tr("Exporter en PDF"),
                           "Navires_" + QDate::currentDate().toString("yyyy-MM-dd") + ".pdf",
                           "PDF Files (*.pdf)");
        if (!fileName.isEmpty()) exportToPDF(fileName);
    });

    connect(actionCsv, &QAction::triggered, this, [this]() {
        QString fileName = QFileDialog::getSaveFileName(this, tr("Exporter en CSV"),
                           "Navires_" + QDate::currentDate().toString("yyyy-MM-dd") + ".csv",
                           "CSV Files (*.csv)");
        if (!fileName.isEmpty()) exportToCSV(fileName);
    });

    if (ui->controlsWidget) {
        ui->controlsWidget->setProperty("role", "toolbarCard");
        ui->controlsWidget->setAttribute(Qt::WA_StyledBackground, true);
    }
    if (tableCard) {
        tableCard->setProperty("role", "tableCard");
        tableCard->setAttribute(Qt::WA_StyledBackground, true);
    }
    if (ui->labelSort) {
        ui->labelSort->setProperty("role", "toolbarLabel");
    }
    if (ui->labelSearch) {
        ui->labelSearch->setProperty("role", "toolbarLabel");
    }

    connect(sortCombo, &QComboBox::currentIndexChanged, this, &NaviresPage::updateSort);
    connect(sortOrderCombo, &QComboBox::currentIndexChanged, this, &NaviresPage::updateSort);
    connect(searchCombo, &QComboBox::currentIndexChanged, this, &NaviresPage::applySearchFilter);
    connect(searchEdit, &QLineEdit::textChanged, this, &NaviresPage::applySearchFilter);
    connect(refreshButton, &QPushButton::clicked, this, &NaviresPage::refreshTable);

    connect(addButton, &QPushButton::clicked, this, &NaviresPage::openAddDialog);

    setupTable();
    applyStyles();
    loadFromDb();
    updateSort();
}

NaviresPage::~NaviresPage()
{
    delete ui;
}

void NaviresPage::setupTable()
{
    if (!table) {
        return;
    }

    table->setColumnCount(9);
    table->setHorizontalHeaderLabels({
        tr("ID"), tr("Nom"), tr("Matricule"), tr("Type"),
        tr("Longueur (m)"), tr("Puissance (CV)"), tr("Propriétaire"), tr("Statut"),
        tr("Actions")
    });

    table->setSelectionBehavior(QAbstractItemView::SelectRows);
    table->setEditTriggers(QAbstractItemView::NoEditTriggers);
    table->setAlternatingRowColors(true);
    table->setSortingEnabled(true);
    table->horizontalHeader()->setDefaultAlignment(Qt::AlignCenter);
    table->horizontalHeader()->setStretchLastSection(false);
    table->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
    table->horizontalHeader()->setSectionResizeMode(1, QHeaderView::Stretch);
    table->horizontalHeader()->setSectionResizeMode(8, QHeaderView::ResizeToContents);
    table->setFrameShape(QFrame::NoFrame);
    table->verticalHeader()->setVisible(false);
    table->setShowGrid(false);
    table->setMouseTracking(true);
    table->viewport()->setMouseTracking(true);
    table->horizontalHeader()->setHighlightSections(false);

    // Hide the ID column — auto-generated by Oracle sequence, not shown to user
    table->setColumnHidden(0, true);
}

static void applyShadow(QWidget *widget, int blur, const QPoint &offset, const QColor &color, qreal opacity)
{
    if (!widget) {
        return;
    }
    auto *effect = new QGraphicsDropShadowEffect(widget);
    QColor tuned = color;
    tuned.setAlphaF(opacity);
    effect->setBlurRadius(blur);
    effect->setOffset(offset);
    effect->setColor(tuned);
    widget->setGraphicsEffect(effect);
}

void NaviresPage::applyStyles()
{
    // Copy the PechePage look-and-feel
    const QString base = QStringLiteral(
        "QWidget#NaviresCrudPage {"
        "  color: #1B1B1B;"
        "  background: transparent;"
        "}"
        "QWidget#NaviresCrudPage QLabel[role=\"toolbarLabel\"] {"
        "  color: #2B2F4A;"
        "  font-weight: 600;"
        "  font-size: 11px;"
        "}"
        "QWidget#NaviresCrudPage QPushButton#btnAddNavire, "
        "QWidget#NaviresCrudPage QPushButton#btnRefresh, "
        "QWidget#NaviresCrudPage QPushButton#btnExport {"
        "  color: #FFFFFF;"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #5E60CE, stop:0.5 #5390D9, stop:1 #4EA8DE);"
        "  border: 1px solid rgba(82, 92, 196, 200);"
        "  border-radius: 10px;"
        "  padding: 6px 16px;"
        "  min-height: 30px;"
        "}"
        "QWidget#NaviresCrudPage QPushButton#btnAddNavire:hover, "
        "QWidget#NaviresCrudPage QPushButton#btnRefresh:hover, "
        "QWidget#NaviresCrudPage QPushButton#btnExport:hover {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #6A58E6, stop:0.6 #4EA8DE, stop:1 #48BFE3);"
        "  border-color: rgba(72, 191, 227, 220);"
        "}"
        "QWidget#NaviresCrudPage QPushButton#btnAddNavire:pressed, "
        "QWidget#NaviresCrudPage QPushButton#btnRefresh:pressed, "
        "QWidget#NaviresCrudPage QPushButton#btnExport:pressed {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #4B4FB8, stop:0.6 #3D8FD3, stop:1 #3A8CC7);"
        "  border-color: rgba(60, 112, 180, 220);"
        "}"
    );

    const QString inputStyle = QStringLiteral(
        "QWidget#NaviresCrudPage QComboBox, "
        "QWidget#NaviresCrudPage QLineEdit {"
        "  color: #1B1B1B;"
        "  background-color: rgba(248, 250, 255, 230);"
        "  border: 1px solid rgba(83, 144, 217, 180);"
        "  border-radius: 10px;"
        "  padding: 6px 10px;"
        "  min-height: 30px;"
        "}"
        "QWidget#NaviresCrudPage QComboBox:focus, "
        "QWidget#NaviresCrudPage QLineEdit:focus {"
        "  border: 2px solid rgba(72, 191, 227, 210);"
        "}"
        "QWidget#NaviresCrudPage QComboBox::drop-down {"
        "  subcontrol-origin: padding;"
        "  subcontrol-position: top right;"
        "  width: 20px;"
        "  border-left: 1px solid rgba(94, 96, 206, 150);"
        "}"
        "QWidget#NaviresCrudPage QComboBox QAbstractItemView {"
        "  background-color: #FFFFFF;"
        "  color: #1B1B1B;"
        "  selection-background-color: rgba(72, 191, 227, 80);"
        "}"
    );

    const QString cardStyle = QStringLiteral(
        "QWidget#NaviresCrudPage QWidget[role=\"toolbarCard\"] {"
        "  background: rgba(248, 250, 255, 230);"
        "  border: 1px solid rgba(83, 144, 217, 120);"
        "  border-bottom: none;"
        "  border-top-left-radius: 14px;"
        "  border-top-right-radius: 14px;"
        "}"
        "QWidget#NaviresCrudPage QWidget#tableCard {"
        "  background: rgba(250, 252, 255, 240);"
        "  border: 1px solid rgba(83, 144, 217, 120);"
        "  border-top: none;"
        "  border-bottom-left-radius: 14px;"
        "  border-bottom-right-radius: 14px;"
        "}"
        "QWidget#NaviresCrudPage QTableWidget#tableNavires {"
        "  background-color: transparent;"
        "  alternate-background-color: rgba(78, 168, 222, 12);"
        "  color: #1B1B1B;"
        "  gridline-color: rgba(0, 0, 0, 18);"
        "  border: none;"
        "  font-size: 11px;"
        "}"
        "QWidget#NaviresCrudPage QTableWidget#tableNavires::item {"
        "  padding: 8px 6px;"
        "  color: #1B1B1B;"
        "  border: 1px solid transparent;"
        "  border-radius: 8px;"
        "}"
        "QWidget#NaviresCrudPage QTableWidget#tableNavires::item:selected {"
        "  background-color: rgba(83, 144, 217, 70);"
        "  border: 1px solid rgba(83, 144, 217, 140);"
        "}"
        "QWidget#NaviresCrudPage QTableWidget#tableNavires::item:hover {"
        "  background-color: rgba(78, 168, 222, 40);"
        "  border: 1px solid rgba(78, 168, 222, 120);"
        "}"
        "QWidget#NaviresCrudPage QHeaderView::section {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #5E60CE, stop:0.6 #5390D9, stop:1 #4EA8DE);"
        "  color: #FFFFFF;"
        "  font-weight: 600;"
        "  font-size: 12px;"
        "  padding: 10px 8px;"
        "  border: none;"
        "  border-bottom: 1px solid rgba(255, 255, 255, 60);"
        "}"
        "QWidget#NaviresCrudPage QTableCornerButton::section {"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #5E60CE, stop:0.6 #5390D9, stop:1 #4EA8DE);"
        "  border: none;"
        "}"
    );

    const QString actionButton = QStringLiteral(
        "QWidget#NaviresCrudPage QToolButton#btnEdit, "
        "QWidget#NaviresCrudPage QToolButton#btnDelete {"
        "  color: #4C57A7;"
        "  background-color: rgba(90, 104, 206, 20);"
        "  border: 1px solid rgba(90, 104, 206, 140);"
        "  border-radius: 8px;"
        "  min-width: 30px;"
        "  max-width: 30px;"
        "  min-height: 30px;"
        "  max-height: 30px;"
        "  font-size: 12px;"
        "}"
        "QWidget#NaviresCrudPage QToolButton#btnEdit:hover, "
        "QWidget#NaviresCrudPage QToolButton#btnDelete:hover {"
        "  color: #FFFFFF;"
        "  background: qlineargradient(x1:0, y1:0, x2:1, y2:0,"
        "    stop:0 #5E60CE, stop:1 #4EA8DE);"
        "  border-color: rgba(72, 191, 227, 200);"
        "}"
        "QWidget#NaviresCrudPage QToolButton#btnEdit:pressed, "
        "QWidget#NaviresCrudPage QToolButton#btnDelete:pressed {"
        "  background: rgba(62, 98, 168, 220);"
        "  border-color: rgba(62, 98, 168, 220);"
        "}"
    );

    setStyleSheet(base + inputStyle + cardStyle + actionButton);

    applyShadow(ui->controlsWidget, 18, QPoint(0, 4), QColor(21, 29, 66), 0.18);
    applyShadow(tableCard, 18, QPoint(0, 6), QColor(21, 29, 66), 0.18);
}

void NaviresPage::loadFromDb()
{
    if (!table) {
        return;
    }

    table->setSortingEnabled(false);
    table->setRowCount(0);

    Navire n;
    QSqlQueryModel *qModel = n.afficher("IDNAVIRE", "ASC");
    if (!qModel) {
        table->setSortingEnabled(true);
        return;
    }

    for (int i = 0; i < qModel->rowCount(); ++i) {
        const int id = qModel->record(i).value(0).toInt();
        const int row = table->rowCount();
        table->insertRow(row);
        table->setRowHeight(row, 50);

        // Fill data columns
        for (int col = 0; col < 7; ++col) {
            const QString cell = qModel->record(i).value(col).toString();
            auto *item = new QTableWidgetItem(cell);
            item->setTextAlignment(Qt::AlignCenter);
            table->setItem(row, col, item);
        }

        // Status column (col 7)
        const QString status = qModel->record(i).value(7).toString();
        table->setCellWidget(row, 7, createStatusBadge(status));

        // Actions column (col 8)
        table->setCellWidget(row, 8, createActionsWidget(id));
    }

    delete qModel;
    table->setSortingEnabled(true);
    applySearchFilter();
}

QWidget *NaviresPage::createActionsWidget(int idNavire)
{
    auto *wrapper = new QWidget();
    auto *layout = new QHBoxLayout(wrapper);
    layout->setContentsMargins(0, 0, 0, 0);
    layout->setSpacing(6);
    layout->setAlignment(Qt::AlignCenter);

    auto *editButton = new QToolButton(wrapper);
    editButton->setText(QStringLiteral(u"✏️"));
    editButton->setToolTip(tr("Modifier navire"));
    editButton->setObjectName("btnEdit");
    editButton->setProperty("idNavire", idNavire);

    auto *deleteButton = new QToolButton(wrapper);
    deleteButton->setText(QStringLiteral(u"🗑️"));
    deleteButton->setToolTip(tr("Supprimer navire"));
    deleteButton->setObjectName("btnDelete");
    deleteButton->setProperty("idNavire", idNavire);

    layout->addWidget(editButton);
    layout->addWidget(deleteButton);

    connect(editButton, &QToolButton::clicked, this, [this, editButton]() {
        const int id = editButton->property("idNavire").toInt();
        openEditDialog(id);
    });
    connect(deleteButton, &QToolButton::clicked, this, [this, deleteButton]() {
        const int id = deleteButton->property("idNavire").toInt();
        confirmDelete(id);
    });

    return wrapper;
}

QWidget* NaviresPage::createStatusBadge(const QString &statut)
{
    auto *wrapper = new QWidget();
    auto *layout = new QHBoxLayout(wrapper);
    layout->setContentsMargins(0,0,0,0);
    layout->setAlignment(Qt::AlignCenter);
    
    auto *label = new QLabel(statut);
    label->setAlignment(Qt::AlignCenter);
    label->setFixedSize(110, 24);
    
    QString baseStyle = "border-radius: 12px; font-weight: bold; font-size: 11px; padding: 2px 8px;";
    
    QString s = statut.toLower();
    if (s.contains("actif") || s.contains("mer") || s.contains("opération") || s.contains("active")) {
        label->setStyleSheet(baseStyle + "background-color: #e6fffa; color: #047857; border: 1px solid #047857;");
    } else if (s.contains("maintenance") || s.contains("réparation") || s.contains("panne") || s.contains("broken")) {
        label->setStyleSheet(baseStyle + "background-color: #fff5f5; color: #c53030; border: 1px solid #c53030;");
    } else if (s.contains("inactif") || s.contains("attente") || s.contains("quai")) {
        label->setStyleSheet(baseStyle + "background-color: #fffaf0; color: #b7791f; border: 1px solid #b7791f;"); // Orange/Yellow
    } else {
        label->setStyleSheet(baseStyle + "background-color: #edf2f7; color: #4a5568; border: 1px solid #4a5568;");
    }
    
    layout->addWidget(label);
    return wrapper;
}

void NaviresPage::openAddDialog()
{
    NavireCrudDialog dlg(NavireCrudDialog::AddMode, this);
    if (dlg.exec() == QDialog::Accepted) refreshTable();
}

void NaviresPage::openEditDialog(int idNavire)
{
    if (idNavire <= 0) return;
    NavireCrudDialog dlg(NavireCrudDialog::EditMode, idNavire, this);
    if (dlg.exec() == QDialog::Accepted) refreshTable();
}

void NaviresPage::confirmDelete(int idNavire)
{
    if (idNavire <= 0) return;

    QMessageBox box(QMessageBox::Question,
                    tr("Confirmation"),
                    tr("Supprimer le navire ID %1 ?").arg(idNavire),
                    QMessageBox::Yes | QMessageBox::No,
                    this);
    box.setStyleSheet(QStringLiteral(
        "QMessageBox {"
        "  background-color: #ffffff;"
        "}"
        "QLabel {"
        "  color: #111111;"
        "}"
        "QPushButton {"
        "  background-color: #325aa4;"
        "  color: #ffffff;"
        "  border: none;"
        "  border-radius: 6px;"
        "  padding: 6px 14px;"
        "  font-weight: 600;"
        "}"
        "QPushButton:hover {"
        "  background-color: #1e3a8a;"
        "}"
    ));
    const auto reply = box.exec();
    if (reply != QMessageBox::Yes) return;

    if (!Navire::supprimer(idNavire)) {
        QMessageBox errBox(QMessageBox::Warning,
                           tr("Erreur SQL"),
                           tr("Suppression impossible."),
                           QMessageBox::Ok,
                           this);
        errBox.setStyleSheet(box.styleSheet());
        errBox.exec();
        return;
    }
    refreshTable();
}

void NaviresPage::updateSort()
{
    if (!table) return;

    int column = 0;
    switch (sortCombo ? sortCombo->currentIndex() : 0) {
    case 0: column = 0; break; // ID
    case 1: column = 1; break; // Nom
    case 2: column = 2; break; // Matricule
    case 3: column = 3; break; // Type
    case 4: column = 6; break; // Proprietaire
    case 5: column = 7; break; // Statut
    default: column = 0; break;
    }

    const Qt::SortOrder order = (sortOrderCombo && sortOrderCombo->currentIndex() == 1)
                                    ? Qt::DescendingOrder
                                    : Qt::AscendingOrder;
    table->sortItems(column, order);
    table->horizontalHeader()->setSortIndicator(column, order);
}

void NaviresPage::applySearchFilter()
{
    if (!table) return;

    const QString filter = searchEdit ? searchEdit->text().trimmed() : QString();

    int column = 0;
    switch (searchCombo ? searchCombo->currentIndex() : 0) {
    case 0: column = 0; break; // ID
    case 1: column = 1; break; // Nom
    case 2: column = 2; break; // Matricule
    case 3: column = 3; break; // Type
    case 4: column = 6; break; // Proprietaire
    case 5: column = 7; break; // Statut
    default: column = 0; break;
    }

    for (int row = 0; row < table->rowCount(); ++row) {
        QTableWidgetItem *item = table->item(row, column);
        const QString text = item ? item->text() : QString();
        const bool match = filter.isEmpty() || text.contains(filter, Qt::CaseInsensitive);
        table->setRowHidden(row, !match);
    }
}

void NaviresPage::refreshTable()
{
    loadFromDb();
    updateSort();
}

void NaviresPage::exportToPDF(const QString &filePath)
{
    if (filePath.isEmpty()) return;

    QPdfWriter pdfWriter(filePath);
    pdfWriter.setPageSize(QPageSize(QPageSize::A4));
    pdfWriter.setPageOrientation(QPageLayout::Landscape);
    pdfWriter.setPageMargins(QMarginsF(15, 15, 15, 15));

    QPainter painter(&pdfWriter);
    if (!painter.isActive()) return;

    int width = pdfWriter.width();
    int height = pdfWriter.height();

    // 1. Header Background - Premium Blue Gradient Style
    painter.fillRect(0, 0, width, 1200, QColor(83, 144, 217));

    // 2. Title and Info
    painter.setPen(Qt::white);
    painter.setFont(QFont("Arial", 22, QFont::Bold));
    painter.drawText(0, 0, width, 800, Qt::AlignCenter, tr("RAPPORT DE LA FLOTTE DE NAVIRES"));
    
    painter.setFont(QFont("Arial", 10));
    painter.drawText(0, 800, width - 500, 300, Qt::AlignRight, 
                     tr("Généré le: ") + QDateTime::currentDateTime().toString("dd/MM/yyyy HH:mm"));

    // 3. Table Headers
    int y = 1400;
    int rowHeight = 450;
    QStringList headers = {tr("ID"), tr("Nom"), tr("Matricule"), tr("Type"), tr("Longueur"), tr("Puissance"), tr("Propriétaire"), tr("Statut")};
    QVector<int> colWidths = { width/15, width/6, width/8, width/8, width/10, width/10, width/6, width/12 };
    
    // Header Row Background
    painter.fillRect(0, y, width, rowHeight, QColor(240, 245, 255));
    painter.setPen(QColor(40, 60, 100));
    painter.setFont(QFont("Arial", 10, QFont::Bold));
    
    int x = 0;
    for (int i = 0; i < headers.size(); ++i) {
        painter.drawText(x + 100, y, colWidths[i] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, headers[i]);
        x += colWidths[i];
    }
    
    y += rowHeight + 100;
    painter.setPen(QColor(200, 200, 200));
    painter.drawLine(0, y - 50, width, y - 50);

    // 4. Table Data
    painter.setFont(QFont("Arial", 9));
    Navire n;
    QSqlQueryModel *model = n.afficher("IDNAVIRE", "ASC");
    if (!model) return;

    for (int i = 0; i < model->rowCount(); ++i) {
        if (y > height - 1000) {
            pdfWriter.newPage();
            y = 500;
            // Draw header again on new page if desired, or just continue
        }

        // Alternating row background for better readability
        if (i % 2 == 1) {
            painter.fillRect(0, y, width, rowHeight, QColor(252, 253, 255));
        }

        painter.setPen(QColor(50, 50, 50));
        x = 0;
        
        // Data columns (0-6)
        painter.drawText(x + 100, y, colWidths[0] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(0).toString()); x += colWidths[0];
        painter.drawText(x + 100, y, colWidths[1] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(1).toString()); x += colWidths[1];
        painter.drawText(x + 100, y, colWidths[2] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(2).toString()); x += colWidths[2];
        painter.drawText(x + 100, y, colWidths[3] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(3).toString()); x += colWidths[3];
        painter.drawText(x + 100, y, colWidths[4] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(4).toString() + " m"); x += colWidths[4];
        painter.drawText(x + 100, y, colWidths[5] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(5).toString() + " CV"); x += colWidths[5];
        painter.drawText(x + 100, y, colWidths[6] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, model->record(i).value(6).toString()); x += colWidths[6];
        
        // Status with color coding (column 7)
        QString status = model->record(i).value(7).toString();
        QString s = status.toLower();
        QColor statusColor(80, 80, 80); // Default
        
        if (s.contains("actif") || s.contains("mer") || s.contains("opération") || s.contains("active")) {
            statusColor = QColor(0, 150, 0); // Solid Green for PDF
        } else if (s.contains("maintenance") || s.contains("réparation") || s.contains("panne") || s.contains("broken")) {
            statusColor = QColor(200, 0, 0); // Solid Red for PDF
        } else if (s.contains("inactif") || s.contains("attente") || s.contains("quai")) {
            statusColor = QColor(200, 120, 0); // Solid Orange for PDF
        }
        
        painter.setPen(statusColor);
        painter.setFont(QFont("Arial", 9, QFont::Bold));
        painter.drawText(x + 100, y, colWidths[7] - 200, rowHeight, Qt::AlignVCenter | Qt::AlignLeft, status);
        painter.setFont(QFont("Arial", 9)); // Reset font
        
        y += rowHeight;
    }
    delete model;

    painter.end();
    QMessageBox::information(this, tr("Export PDF"), tr("Le rapport PDF premium coloré a été généré avec succès."));
}

void NaviresPage::exportToCSV(const QString &filePath)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) return;

    QTextStream out(&file);
    out.setGenerateByteOrderMark(true);

    // Header
    out << "ID;Nom;Matricule;Type;Longueur (m);Puissance (CV);Proprietaire;Statut\n";

    Navire n;
    QSqlQueryModel *model = n.afficher("IDNAVIRE", "ASC");
    if (model) {
        for (int i = 0; i < model->rowCount(); ++i) {
            out << model->record(i).value(0).toString() << ";"
                << model->record(i).value(1).toString() << ";"
                << model->record(i).value(2).toString() << ";"
                << model->record(i).value(3).toString() << ";"
                << model->record(i).value(4).toString() << ";"
                << model->record(i).value(5).toString() << ";"
                << model->record(i).value(6).toString() << ";"
                << model->record(i).value(7).toString() << "\n";
        }
        delete model;
    }

    file.close();
    QMessageBox::information(this, tr("Export CSV"), tr("Le fichier CSV a été généré avec succès."));
}
